apiVersion: v1
kind: Service
metadata:
  name: javaproject-service
spec:
  type: NodeBalancer
  selector:
    app: javaproject
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
